### PR TITLE
Fix: Enforce brake and speed checks for Race Mode

### LINKED ISSUE #453: Add mode change requirements
Currently you can enter race mode while on the pedal and while moving. Change this to require the car to be stopped and the brake to be applied

### PR DESCRIPTION
**Pull request by luckys00**
## Summary
This PR implements safety checks for switching to Race Mode, as requested in issue #453.

## Changes
- Updated `evaluate_mode_change` in `torque.c` to accept `brake_position`.
- Added logic to ensure the vehicle speed is 0 AND the brake is pressed (>10%) before allowing the mode switch.
- Updated the function call in `torque_periodic_100Hz` to pass the brake position.

## Ticket
Fixes #453

### CODE REVIEW

File: components/vc/front/src/torque.c [hunk 1]
```diff
@@ -134,7 +134,12 @@ static bool evaluate_mode_change(void)
                                           (race_mode_change_requested == CAN_DIGITALSTATUS_ON);
     const bool race_mode_change_rising = !race_mode_change_was_requested && torque_data.race_mode_change_active;
 
-    if (race_mode_change_rising)
+    const float32_t vehicleSpeed = wheelSpeed_getAxleRPM(AXLE_FRONT);
```
Comment (rickyelopez) [inline components/vc/front/src/torque.c]: feels like there should be a validity check here too, i.e. checking that the wheel speed from the front axle is valid

File: components/vc/front/src/torque.c [hunk 2]
```diff
@@ -134,7 +134,12 @@ static bool evaluate_mode_change(void)
...
+    const bool safety_checks_ok = (brake_position > PEDAL_APPLIED_THRESHOLD) &&
+                                  (vehicleSpeed < VEHICLE_STOPPED_THRESHOLD);
+
+
+    if (race_mode_change_rising && safety_checks_ok)
```
Comment (rickyelopez) [inline components/vc/front/src/torque.c]: constants like this are free
```suggestion
    const bool brakePedalPressed = brake_position > PEDAL_APPLIED_THRESHOLD;
    const bool vehicleStationary = vehicleSpeed < VEHICLE_STOPPED_THRESHOLD;


    if (race_mode_change_rising && brakePedalPressed && vehicleStationary)
```

File: components/vc/front/src/torque.c [hunk 3]
```diff
@@ -145,7 +146,12 @@ static bool evaluate_mode_change(void)
                                           (race_mode_change_requested == CAN_DIGITALSTATUS_ON);
     const bool race_mode_change_rising = !race_mode_change_was_requested && torque_data.race_mode_change_active;
 
-    if (race_mode_change_rising)
+    const float32_t vehicleSpeed = app_vehicleSpeed_getVehicleSpeed();
+
+    const bool brakePedalPressed = brake_position > PEDAL_APPLIED_THRESHOLD;
+    const bool vehicleStationary = vehicleSpeed < VEHICLE_STOPPED_THRESHOLD;
```
Comment (rickyelopez) [inline components/vc/front/src/torque.c]: probably use `>=` here

**Comment by luckys00** [comment]
@rickyelopez 
Done! I updated the safety check to use >= and squashed everything into a single commit.

**Comment by luckys00** [comment]
Hi @rickyelopez, just a gentle reminder to review this when you get a chance. I've addressed the feedback and squashed the commits. Thanks!

**Review by joshlafleur-zip — APPROVED** [review]
lgtm, but probably good to wait for ricky also (itll take a few days to get someone to test the code before merging).

Also would be good to make a test plan like https://github.com/concordia-fsae/firmware/pull/459, but tbh there I was a bit lazy.

Something like:
- With brakes applied at <10%, ensure reverse requests are rejected
- With the car moving over 0.5m/s, ensure reverse requests are rejected
- With the car stopped and with the brakes applied, ensure the vehicle transitions into reverse

@freeman803 could support testing, he will be at the workshop and I can reach out to him directly, lets validate the code before merging
